name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
          
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - uses: jetli/wasm-bindgen-action@v0.2.0
      with:
        version: 'latest'
        
    - uses: actions/checkout@v3
    
    - run: trunk build --release
    
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
          github_token: $
          publish_dir: ./dist
